# ===============================
# DEVELOPMENT PROFILE
# ===============================

# ===============================
# H2 DATABASE CONFIGURATION
# ===============================
# Enable H2 web console
spring.h2.console.enabled=true
# Set the path for the H2 console
spring.h2.console.path=/h2-console

# ===============================
# DATASOURCE CONFIGURATION
# ===============================
# The DB_CLOSE_DELAY=-1 parameter keeps the in-memory database alive for the duration of the JVM,
# allowing the H2 console to connect to the same database instance used by the application.
spring.datasource.url=jdbc:h2:mem:dozendb;DB_CLOSE_DELAY=-1
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

# ===============================
# JPA / HIBERNATE CONFIGURATION
# ===============================
# Show SQL statements in the console for debugging
spring.jpa.show-sql=true
# Disable the Open Session in View pattern for better performance and resource management in REST APIs.
spring.jpa.open-in-view=false
