-- Baseline: reproduces the schema Hibernate auto-generated for the `tasks`
-- table before Flyway was introduced. Flyway is baselined at this version in
-- every environment that already has this table (see baseline-on-migrate /
-- baseline-version in application-prod.properties.example and README.md),
-- so this script never actually runs against an existing database — it only
-- runs when Flyway builds a brand-new schema from scratch (fresh H2/dev DB).
CREATE TABLE tasks (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title VARCHAR(255) NOT NULL,
    description VARCHAR(255),
    status VARCHAR(255) NOT NULL,
    task_order INTEGER NOT NULL
);
