CREATE TABLE labels (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(255),
    color_hex VARCHAR(7) NOT NULL
);

CREATE TABLE task_labels (
    task_id BIGINT NOT NULL REFERENCES tasks(id) ON DELETE CASCADE,
    label_id BIGINT NOT NULL REFERENCES labels(id) ON DELETE CASCADE,
    PRIMARY KEY (task_id, label_id)
);

-- Seed the classic Trello label palette (unnamed swatches, same as a brand
-- new Trello board) so the picker has ready-to-use colors from day one;
-- users can rename or add more via the labels API.
INSERT INTO labels (name, color_hex) VALUES
    (NULL, '#61bd4f'),
    (NULL, '#f2d600'),
    (NULL, '#ff9f1a'),
    (NULL, '#eb5a46'),
    (NULL, '#c377e0'),
    (NULL, '#0079bf'),
    (NULL, '#00c2e0'),
    (NULL, '#51e898');
