-- Replaces the fixed 3-value `status` enum column on `tasks` with a real,
-- user-manageable `task_lists` table (dynamic Trello-style columns), and
-- adds archive/restore support (soft-delete) for both lists and tasks.

CREATE TABLE task_lists (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    position INTEGER NOT NULL,
    archived BOOLEAN NOT NULL DEFAULT FALSE
);

-- Seeds the 3 existing hardcoded columns in their current order. This table
-- is brand new in every environment this migration runs against, so
-- IDENTITY is guaranteed to hand out 1/2/3 here (same reasoning
-- V3__create_labels.sql relies on for its own seed rows).
INSERT INTO task_lists (name, position) VALUES
    ('A Fazer', 0),
    ('Em Andamento', 1),
    ('Concluída', 2);

ALTER TABLE tasks ADD COLUMN list_id BIGINT;

UPDATE tasks SET list_id = CASE status
    WHEN 'A_FAZER' THEN 1
    WHEN 'EM_ANDAMENTO' THEN 2
    WHEN 'CONCLUIDA' THEN 3
END;

ALTER TABLE tasks ALTER COLUMN list_id SET NOT NULL;

-- ON DELETE CASCADE backs the permanent hard-delete path (only reachable
-- from the archive panel once a list has already been archived) so
-- deleting a list for good also clears out its tasks.
ALTER TABLE tasks ADD CONSTRAINT fk_tasks_list_id
    FOREIGN KEY (list_id) REFERENCES task_lists(id) ON DELETE CASCADE;

CREATE INDEX idx_tasks_list_id ON tasks(list_id);

ALTER TABLE tasks ADD COLUMN archived BOOLEAN NOT NULL DEFAULT FALSE;

ALTER TABLE tasks DROP COLUMN status;
